# These are supported funding model platforms

github: h4cklinker
patreon: h4cklinker
open_collective: h4cklinker
ko_fi: h4cklinker
tidelift: web site / linux server
community_bridge: github
liberapay: h4linker
issuehunt: h4linker
otechie: h4cklinker
custom: h4cklinker.github.io,h4link.duckdns.org
